const API_BASE="http://localhost:8081";const API={subjects:`${API_BASE}/Subject`,reminders:`${API_BASE}/Reminder`,timetable:`${API_BASE}/timeTableEntry`};let subjects=[],reminders=[],selected=new Date();selected.setHours(0,0,0,0);
const $=x=>document.getElementById(x);const key=d=>{d=new Date(d);return `${d.getFullYear()}-${d.getMonth()}-${d.getDate()}`};const fmt=d=>new Intl.DateTimeFormat("en-IN",{day:"numeric",month:"short",year:"numeric"}).format(new Date(d));const time=v=>{let d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleTimeString("en-IN",{hour:"numeric",minute:"2-digit"})};const getSid=r=>r.subjectId??r.subject?.id??r.routineId??null;const subjectName=r=>r.subject?.title||r.subjectTitle||subjects.find(s=>String(s.id)===String(getSid(r)))?.title||"General";const subjectColor=r=>r.subject?.color||subjects.find(s=>String(s.id)===String(getSid(r)))?.color||"#685cff";
async function req(url,opt={}){let r=await fetch(url,opt);if(!r.ok)throw Error(`${r.status}`);let t=await r.text();return t?JSON.parse(t):null}
async function load(){ $("status").textContent="Loading...";try{let [s,r]=await Promise.all([req(API.subjects),req(API.reminders)]);subjects=Array.isArray(s)?s:[];reminders=Array.isArray(r)?r:[];$("status").textContent=`${reminders.length} reminder${reminders.length==1?"":"s"} loaded.`;days();renderTime();renderRoutine();populate()}catch(e){$("status").textContent="Could not connect to Spring Boot. Check port 8081 and your controller mappings.";console.error(e)}}
function days(){let d=new Date(selected),n=d.getDay(),off=n===0?-6:1-n;d.setDate(d.getDate()+off);$("days").innerHTML="";for(let i=0;i<7;i++){let x=new Date(d);x.setDate(d.getDate()+i);let b=document.createElement("button");b.className="day"+(key(x)==key(selected)?" active":"");b.innerHTML=`<strong>${x.toLocaleDateString("en-IN",{weekday:"short"})}</strong><small>${x.getDate()} ${x.toLocaleDateString("en-IN",{month:"short"})}</small>`;b.onclick=()=>{selected=new Date(x);renderTime();days()};$("days").append(b)}}
function renderTime(){$("date").textContent=fmt(selected).toUpperCase();$("day").textContent=selected.toLocaleDateString("en-IN",{weekday:"long"});let arr=reminders.filter(r=>r.deadline&&key(r.deadline)==key(selected)).sort((a,b)=>new Date(a.deadline)-new Date(b.deadline));$("cards").innerHTML="";if(!arr.length){$("cards").innerHTML='<div class="empty">No reminders for this day.</div>';return}arr.forEach(r=>$("cards").append(card(r)))}
function card(r){let e=document.createElement("article");e.className="card";e.style.borderLeftColor=subjectColor(r);e.innerHTML=`<div><h3></h3><p></p><div class="meta"><span class="pill subjectPill"></span><span class="pill"></span><span class="pill repeat"></span></div></div><div class="actions"><button class="done"></button><button class="edit">Edit</button><button class="danger del">Delete</button></div>`;e.querySelector("h3").textContent=r.title||"Untitled";e.querySelector("p").textContent=r.description||"No description";e.querySelector(".subjectPill").textContent=subjectName(r);e.querySelector(".pill:not(.subjectPill)").textContent=`Deadline · ${time(r.deadline)}`;e.querySelector(".repeat").textContent=`Repeat · ${r.repeatType||"NONE"}`;e.querySelector(".done").textContent=r.completed?"Completed":"Complete";e.querySelector(".done").onclick=()=>complete(r);e.querySelector(".edit").onclick=()=>openEdit(r);e.querySelector(".del").onclick=()=>del(r.id);return e}
function renderRoutine(){let q=$("search").value.toLowerCase();$("routines").innerHTML="";subjects.filter(s=>(s.title||"").toLowerCase().includes(q)).forEach(s=>{let rs=reminders.filter(r=>String(getSid(r))===String(s.id));let e=document.createElement("article");e.className="routine";e.style.setProperty("--c",s.color||"#685cff");e.innerHTML=`<div class="bar"></div><div class="body"><h3></h3><p class="count"></p><div class="list"></div></div>`;e.querySelector("h3").textContent=s.title;e.querySelector(".count").textContent=`${rs.length} reminder${rs.length==1?"":"s"}`;rs.forEach(r=>{let m=document.createElement("div");m.className="mini";m.innerHTML="<b></b><span></span>";m.querySelector("b").textContent=r.title;m.querySelector("span").textContent=`${fmt(r.deadline)} · ${time(r.deadline)}`;e.querySelector(".list").append(m)});$("routines").append(e)});if(!$("routines").children.length)$("routines").innerHTML='<div class="empty">No subjects found.</div>'}
function populate(){$("subject").innerHTML='<option value="">Select subject</option>';subjects.forEach(s=>{let o=document.createElement("option");o.value=s.id;o.textContent=s.title;$("subject").append(o)})}
function inputDate(v){let d=new Date(v);if(Number.isNaN(d.getTime()))return"";let p=n=>String(n).padStart(2,"0");return`${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`}
function openNew(){$("form").reset();$("rid").value="";$("dialogTitle").textContent="New reminder";$("deadline").value=inputDate(new Date());$("dlg").showModal()}
function openEdit(r){$("rid").value=r.id;$("rt").value=r.title||"";$("rd").value=r.description||"";$("deadline").value=inputDate(r.deadline);$("repeat").value=r.repeatType||"NONE";$("subject").value=getSid(r)||"";$("dialogTitle").textContent="Edit reminder";$("dlg").showModal()}
async function save(e){e.preventDefault();let id=$("rid").value,p={title:$("rt").value.trim(),description:$("rd").value.trim(),deadline:new Date($("deadline").value).toISOString(),repeatType:$("repeat").value,completed:false};if($("subject").value)p.subjectId=Number($("subject").value);try{await req(id?`${API.reminders}/${id}`:API.reminders,{method:id?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(p)});$("dlg").close();load()}catch(e){$("status").textContent="Could not save reminder. Check ReminderController mapping/body.";console.error(e)}}
async function complete(r){try{await req(`${API.reminders}/${r.id}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({...r,completed:!r.completed})});load()}catch(e){console.error(e)}}
async function del(id){if(!confirm("Delete this reminder?"))return;try{await req(`${API.reminders}/${id}`,{method:"DELETE"});load()}catch(e){console.error(e)}}
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll("nav button").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("time").classList.toggle("hide",b.dataset.view!=="time");$("routine").classList.toggle("hide",b.dataset.view!=="routine");$("title").textContent=b.dataset.view==="time"?"Timetable":"Routines";$("sub").textContent=b.dataset.view==="time"?"Your reminders, organised day by day.":"All your reminders, organised subject wise."});
$("new").onclick=openNew;$("refresh").onclick=load;$("search").oninput=renderRoutine;$("close").onclick=()=>$("dlg").close();$("cancel").onclick=()=>$("dlg").close();$("form").onsubmit=save;days();load();